version: "5.4"

services:
 app:
  build: ./docker/php/.
  container_name: php
  working_dir: /var/www/app
  volumes:
   - ./app:/var/www/app
  networks:
   - notenapp

 nginx:
  image: nginx:alpine
  container_name: nginx
  working_dir: /var/www/app
  ports:
   - 8001:80
  volumes:
   - ./app:/var/www/app
   - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  networks:
   - notenapp

 mysql:
  image: mariadb:latest
  container_name: mariadb
  restart: always
  environment:
   - MARIADB_DATABASE=dbone
   - MARIADB_ROOT_PASSWORD=root
   - MARIADB_USER=user
   - MARIADB_PASSWORD=userpass
  volumes:
   - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
  ports:
   - 3306:3306
  networks:
   - notenapp

networks:
 notenapp:
  driver: bridge
